### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by 1c7** [dx0x58/Treehouse-dl#3]
![image](https://cloud.githubusercontent.com/assets/1804755/12350916/053b17be-bbb5-11e5-930f-d35d6e15e8ce.png)

Python3.4
Windows 10

**Comment by charanrain** [comment]
Me too same error.

**Comment by muthusankar54** [comment]
i am facing the following issue while run main.py file

Muthu@Muthu-VAIO MINGW64 /c/TreeHouse/Treehouse-Saver (master)
$ python main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "C:\Python36-32\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Python36-32\lib\site-packages\bs4\builder\__init__.py", line 308, in                                                                                                                 <module>
    from . import _htmlparser
  File "C:\Python36-32\lib\site-packages\bs4\builder\_htmlparser.py", line 7, in                                                                                                                 <module>
    from html.parser import (
ImportError: cannot import name 'HTMLParseError'

**Comment by ab-anand** [comment]
`pip install --upgrade beautifulsoup4` This works

**Comment by Adarsh777** [comment]
@1c7  me too getting same error.
